name: Robot with Selenium

on:
  pull_request:
    branches:
      - main

jobs:
  selenium_testing:
    name: Run Selenium testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

        with:
            python-version: 3.x

      - name: Install Chrome for Testing and its driver
        run: |
          npm i puppeteer
          npx @puppeteer/browsers install chrome@stable


      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary



      - name: Start npm
        run: npm install && npm run dev-pipeline

      - name: Run Selenium tests
        run: |
          cd Robot
          robot initial_test.robot
        env:
          BASE_URL: http://localhost:3000
          BROWSER: headlesschrome
